# Generated by Django 5.2.7 on 2025-10-06 19:30

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المكتبة')),
                ('description', models.TextField(blank=True, verbose_name='وصف المكتبة')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('face_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='اسم الشخص')),
                ('description', models.TextField(blank=True, verbose_name='وصف إضافي')),
                ('face_image', models.ImageField(upload_to='faces_images/', verbose_name='صورة الوجه')),
                ('face_embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=128, verbose_name='التمثيل الرقمي (Embedding)')),
                ('is_registered', models.BooleanField(default=False, verbose_name='هل تم استخراج الـ Embedding؟')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='api.facelibrary', verbose_name='المكتبة المرتبطة')),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الحدث')),
                ('is_recognized', models.BooleanField(default=False, verbose_name='هل تم التعرف عليه؟')),
                ('snapshot_image', models.ImageField(blank=True, null=True, upload_to='log_snapshots/', verbose_name='صورة اللقطة')),
                ('log_message', models.CharField(max_length=255, verbose_name='رسالة السجل')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.faceprofile', verbose_name='الشخص المعرف عليه')),
            ],
        ),
    ]
